sudo: false

stages:
  - lint
  - test
  - name: release
    if: branch = master

node_js_defaults: &node_js_defaults
  language: node_js
  node_js: '10'
  cache:
    yarn: true
    directories:
      - node_modules

jobs:
  include:
    - stage: lint
      <<: *node_js_defaults
      script: yarn lint:ci

    - stage: test
      <<: *node_js_defaults
      node_js:
        - '10'
        - '9'
        - '8'
      script: yarn test:ci

    - stage: release
      <<: *node_js_defaults
      script: yarn build
      deploy:
        provider: script
        skip_cleanup: true
        script: yarn semantic-release
